"""add editable fields and morale entries

Revision ID: 62685c417e7c
Revises: c6a85909a3f2
Create Date: 2026-06-15 12:48:15.746441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62685c417e7c'
down_revision: Union[str, None] = 'c6a85909a3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morale_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=False),
    sa.Column('employee', sa.String(length=128), nullable=False),
    sa.Column('week', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('week', sa.String(length=32), nullable=False, server_default=''))
    op.add_column('events', sa.Column('deviation', sa.Text(), nullable=False, server_default=''))
    op.add_column('events', sa.Column('root_cause', sa.Text(), nullable=False, server_default=''))
    op.add_column('events', sa.Column('countermeasure', sa.Text(), nullable=False, server_default=''))
    op.add_column('events', sa.Column('responsible', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('events', sa.Column('term_weeks', sa.String(length=32), nullable=False, server_default=''))
    op.add_column('events', sa.Column('status_code', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('events', sa.Column('closure_confirm', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'closure_confirm')
    op.drop_column('events', 'status_code')
    op.drop_column('events', 'term_weeks')
    op.drop_column('events', 'responsible')
    op.drop_column('events', 'countermeasure')
    op.drop_column('events', 'root_cause')
    op.drop_column('events', 'deviation')
    op.drop_column('events', 'week')
    op.drop_table('morale_entries')
    # ### end Alembic commands ###
