"""initial schema

Revision ID: c6a85909a3f2
Revises: 
Create Date: 2026-06-14 20:57:58.778129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6a85909a3f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identity', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identity', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('day', sa.String(length=32), nullable=False),
    sa.Column('time', sa.String(length=16), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('leader', sa.String(length=255), nullable=False),
    sa.Column('leader_phone', sa.String(length=32), nullable=False),
    sa.Column('quality_owner', sa.String(length=255), nullable=False),
    sa.Column('quality_owner_phone', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('climate_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('latest_week', sa.String(length=64), nullable=False),
    sa.Column('latest_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('curator', sa.String(length=255), nullable=False),
    sa.Column('moscow_yaroslavl', sa.Boolean(), nullable=False),
    sa.Column('electoral_cycle', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('raw_status', sa.String(length=64), nullable=False),
    sa.Column('traffic', sa.String(length=8), nullable=False),
    sa.Column('traffic_label', sa.String(length=32), nullable=False),
    sa.Column('budget', sa.String(length=255), nullable=False),
    sa.Column('is_high_priority', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('is_problem', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('periodicity', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('fact_label', sa.String(length=255), nullable=False),
    sa.Column('target_label', sa.String(length=255), nullable=False),
    sa.Column('latest_period', sa.String(length=64), nullable=False),
    sa.Column('latest_fact', sa.Float(), nullable=True),
    sa.Column('latest_target', sa.Float(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_metrics')
    op.drop_table('events')
    op.drop_table('climate_series')
    op.drop_table('meetings')
    op.drop_table('import_log')
    op.drop_table('departments')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
