"""measures table

Revision ID: ca4d4599fdc6
Revises: 62685c417e7c
Create Date: 2026-06-15 13:12:03.221876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca4d4599fdc6'
down_revision: Union[str, None] = '62685c417e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('week', sa.String(length=32), nullable=False),
    sa.Column('initiator', sa.String(length=255), nullable=False),
    sa.Column('deviation', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('countermeasure', sa.Text(), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=False),
    sa.Column('term_weeks', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('closure_confirm', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measures')
    # ### end Alembic commands ###
